# -*- coding: utf-8 -*-
"""Poly_interp_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-5h5JlldKHg2kP_vUYgC-Jo5zMpFg1k
"""

import pytest
import numpy as np
from interpolacao import Poly_Interp

@pytest.fixture
def sample_data():
    x = [0, 1, 2, 3]
    y = [0, 1, 4, 9] # y = x^2
    return x, y

@pytest.fixture
def poly_interp_instance(sample_data):
    x, y = sample_data
    return Poly_Interp(x, y)

def test_poly_interp_initialization(poly_interp_instance, sample_data):
    x, y = sample_data
    assert np.array_equal(poly_interp_instance.x, np.array(x))
    assert np.array_equal(poly_interp_instance.y, np.array(y))
    assert poly_interp_instance.n == len(x)
    assert poly_interp_instance.domain.min == x[0]
    assert poly_interp_instance.domain.max == x[-1]
    assert poly_interp_instance.coeficientes is not None
    assert len(poly_interp_instance.coeficientes) == poly_interp_instance.n

def test_poly_interp_call_single_value(poly_interp_instance):
    assert np.isclose(poly_interp_instance(0), 0)
    assert np.isclose(poly_interp_instance(1), 1)
    assert np.isclose(poly_interp_instance(2), 4)
    assert np.isclose(poly_interp_instance(3), 9)
    assert np.isclose(poly_interp_instance(1.5), 1.5**2)

def test_poly_interp_call_array_values(poly_interp_instance):
    x_test = np.array([0.5, 1.5, 2.5])
    y_expected = x_test**2
    y_actual = poly_interp_instance(x_test)
    assert np.allclose(y_actual, y_expected)

def test_poly_interp_coefficients():
    x = [0, 1, 2]
    y = [1, 3, 7]
    poly_interp = Poly_Interp(x, y)
    expected_coefficients = np.array([1., 2., 1.])
    assert np.allclose(poly_interp.coeficientes, expected_coefficients)

def test_poly_interp_error_calculation():
    x = [0, 1, 2]
    y = [0, 1, 4] # y = x^2
    poly_interp = Poly_Interp(x, y)

    def original_func(val):
        return val**2

    test_points = [0.5, 1.5, 2.5]

    errors = poly_interp.erro(original_func, test_points)
    expected_errors = np.array([0.0, 0.0, 0.0])
    assert np.allclose(errors, expected_errors, atol=1e-9)

def test_poly_interp_domain_check(poly_interp_instance):
    assert np.isnan(poly_interp_instance(4))
    assert np.isnan(poly_interp_instance(-1))

def test_poly_interp_zero_division_error():
    x_bad = [0, 0, 1]
    y_bad = [0, 1, 2]
    with pytest.raises(ZeroDivisionError, match='Há dois pontos com a mesma coordenada x.'):
        Poly_Interp(x_bad, y_bad)